---
- hosts: localhost
  gather_facts: true
  tasks:
  - name: GET IP ADDRESS
    setup:
    register: result
  - name:  PRINT THE OUTPUT
    debug: var=item.address
    loop: "{{ result.ansible_facts.ansible_eth0.ipv6 }}"
