---
- hosts: all #jumpbox
  gather_facts: true

- name: configure app
  hosts: tag_AnsibleGroup_apps
  become: yes
  gather_facts: false

  roles:
    - {name: repo} 
    - {name: apptier}

- name: configure web
  hosts: tag_AnsibleGroup_frontends
  become: yes
  gather_facts: false

  roles:
    - {name: repo}
    - {name: webtier} 

- name: configure db
  hosts: tag_AnsibleGroup_appdbs
  become: yes
  gather_facts: false

  roles:
    - {name: repo}
    - {name: dbtier}

